export const GET_HEROES_REQUEST = "GET_HEROES_REQUEST"
export const GET_HEROES_SUCCESS = "GET_HEROES_SUCCESS"
export const GET_HEROES_FAILURE = "GET_HEROES_FAILURE"

export const DELETE_HERO_REQUEST = "DELETE_HERO_REQUEST"
export const DELETE_HERO_SUCCESS = "DELETE_HERO_SUCCESS"
export const DELETE_HERO_FAILURE = "DELETE_HERO_FAILURE"